name: Run Newman tests

on:
  workflow_dispatch:

jobs:
  api-testing:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.17.1
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run Newman tests
        run: newman run tests/jsonPlaceholder.postman.json -r htmlextra
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: newman-report
          path: newman/
          retention-days: 7
